### ISSUE TITLE
Runtime exception with the zip-js dependency

### ISSUE THREAD

**Issue by JCCR** [readium/readium-js#173] opened 2017-02-14 23:13 UTC
#### Expected Behaviour
- Not to halt JS execution with an exception when parsing/loading the minified code artifacts of this project

### Observed Behaviour
- Execution halts with an error: `SyntaxError: Functions cannot be declared in a nested block in strict mode `

#### Steps to reproduce
1. Run `npm run prepare`
2. Run `npm run build`
3. Find that the built artifacts include code references to this section of the code in zip-js:
https://github.com/gildas-lormeau/zip.js/blob/master/WebContent/zip-fs.js#L163
4. Try to run a web app built using those artifacts

### Product
* Readium cloud reader app
  * latest development build
  * PhantomJS 2.1
  * macOS Sierra

#### Additional information
This appears to only be an issue on PhantomJS 2.x possibly Safari 8 as well.

**Comment by JCCR** [comment] 2017-02-14 23:24
Filed an issue with the upstream zip-js repo:
https://github.com/gildas-lormeau/zip.js/issues/168

**Comment by bradleygore** [comment] 2017-03-20 15:34
@JCCR I don't think Readium pulls in that zip js repo directly. I believe it pulls in this fork: https://github.com/danielweck/zip.js, so shouldn't the issue you created be on that fork instead of the original repo?

**Comment by danielweck** [comment] 2017-03-20 16:19
Actually, it is correct to expect Juan's reported "bug" (which only seems to occur in old webkit builds like PhantomJS and Safari 8 (?)) to be caused by code in the upstream / original project repository.

In ReadiumJS, this external library is forked in order to add the following code modifications:
https://github.com/gildas-lormeau/zip.js/compare/master...danielweck:master

In fact, note that this is a fork of another fork :)
https://github.com/gildas-lormeau/zip.js/compare/master...ryanackley:master

**Comment by bradleygore** [comment] 2017-03-20 16:34
Yeah, I understand the bug originated in the original repo, I'm just saying that if it's been forked that it may be more quickly resolved within the fork instead of the original - in looking at the original, there's less and less activity when looking at commits from 2015 to current.

This is also affecting Safari 9.

**Comment by danielweck** [comment] 2017-03-20 16:39
Oh, that makes sense!  Thanks :)

**Comment by danielweck** [comment] 2017-03-20 16:44
related issue:
https://github.com/readium/readium-js-viewer/issues/565

**Comment by danielweck** [comment] 2017-05-25 12:28
This was fixed https://github.com/gildas-lormeau/zip.js/pull/170

**Closed by danielweck** 2017-05-25 12:28 UTC
Labels: difficulty:Dev, func:Builds, priority:Medium, status:NotThisProduct, type:Bug
